name: Check

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 'Auto Merge'
        if: github.event.pull_request.user.login == 'ArtARTs36' && startsWith(github.event.pull_request.title, '[AUTO]')
        uses: daneden/enable-automerge-action@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          allowed-author: 'ArtARTs36'
