name: Check

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: 'Auto Merge'
        run: 'echo "kuku"'
        if: github.event.pull_request.user.login == 'artarts36' && startsWith(github.event.pull_request.title, '[AUTO]')
